INSERT INTO cpu (option) VALUES ('Intel 10900kf');
INSERT INTO cpu (option) VALUES ('AMD Ryzen 3700');
INSERT INTO cpu (option) VALUES ('AMD Ryzen 4750GE');

INSERT INTO gpu (option) VALUES ('4GB');
INSERT INTO gpu (option) VALUES ('8GB');
INSERT INTO gpu (option) VALUES ('16GB');

INSERT INTO memory (option) VALUES ('RTX 3060');
INSERT INTO memory (option) VALUES ('RTX 3080');
INSERT INTO memory (option) VALUES ('Radeon RX 6800');